project_dir = '/icgc/dkfzlsdf/analysis/hs_ontogeny'
project_temp_dir = f'{project_dir}/temp'
wgbs_cohort_results_dir = f'{project_dir}/results/wgbs/cohort_results'
wgbs_results_per_pid_dir = f'{project_dir}/results/wgbs/results_per_pid'
wgbs_metadata_dir = f'{project_dir}/results/wgbs/metadata'
